-- =====================================================
-- Author      : Mithun
-- Date        : 2026-07-06
-- Description : Creates the users table. Passwords are
--               never stored in plain text — password_hash
--               holds a BCrypt hash generated by the API.
--               role_id links each user to roles(id).
-- =====================================================
CREATE TABLE users (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role_id       INT NOT NULL REFERENCES roles(id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);